name: boilerplate_fullstack_typescript_local

services:
    backend:
        build:
            context: ..
            dockerfile: ops/Dockerfile.local.backend
        container_name: boilerplate_fullstack_typescript_local_backend
        env_file:
            - ../envs/.env.local.backend
        image: boilerplate_fullstack_typescript:local-backend-0.0.5
        ports:
            - "38502:38502"
        restart: unless-stopped

    frontend:
        build:
            context: ..
            dockerfile: ops/Dockerfile.local.frontend
        container_name: boilerplate_fullstack_typescript_local_frontend
        depends_on:
            - backend
        env_file:
            - ../envs/.env.local.frontend
        image: boilerplate_fullstack_typescript:local-frontend-0.0.5
        ports:
            - "38501:38501"
        restart: unless-stopped
