name: boilerplate_fullstack_typescript_development

services:
    backend:
        build:
            context: ..
            dockerfile: ops/Dockerfile.development.backend
        container_name: boilerplate_fullstack_typescript_development_backend
        env_file:
            - ../envs/.env.development.backend
        image: boilerplate_fullstack_typescript:development-backend-0.0.4
        ports:
            - "38502:38502"
        restart: unless-stopped

    frontend:
        build:
            context: ..
            dockerfile: ops/Dockerfile.development.frontend
        container_name: boilerplate_fullstack_typescript_development_frontend
        depends_on:
            - backend
        env_file:
            - ../envs/.env.development.frontend
        image: boilerplate_fullstack_typescript:development-frontend-0.0.4
        ports:
            - "38501:38501"
        restart: unless-stopped
